package com.curio.app.ui.theme

import androidx.compose.ui.graphics.Color

// ── Light Surface Colors (placeholder — dark theme is primary) ──
val LightSurface = Color(0xFFF2F7F6)
val LightSurfaceDim = Color(0xFFD5E3E1)
val LightSurfaceBright = Color(0xFFF8FCFB)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFEEF5F3)
val LightSurfaceContainer = Color(0xFFE6EFED)
val LightSurfaceContainerHigh = Color(0xFFDDE8E6)
val LightSurfaceContainerHighest = Color(0xFFD4E2DF)

val LightOnSurface = Color(0xFF1B2221)
val LightOnSurfaceVariant = Color(0xFF4E5755)
val LightPrimary = Color(0xFF31736A)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD2F5EE)
val LightOnPrimaryContainer = Color(0xFF00201D)
val LightSecondary = Color(0xFF008A8E)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFB6F4F7)
val LightOnSecondaryContainer = Color(0xFF002021)
val LightTertiary = Color(0xFF7B6B1C)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFE89D)
val LightOnTertiaryContainer = Color(0xFF261F00)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightOutline = Color(0xFF707877)
val LightOutlineVariant = Color(0xFFC0C8C6)
val LightCardGradientStart = Color(0xFFE6F3F0)
val LightCardGradientEnd = Color(0xFFDCEBE7)
val LightAccentGradientStart = Color(0xFF00BCD4)
val LightAccentGradientMid = Color(0xFF31736A)
val LightAccentGradientEnd = Color(0xFFC9A900)
val LightBookmarkActive = Color(0xFFC9A900)
